name: Publish
on:
  push:
    branches:    
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
  
    # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.PUSHER_TOKEN }}
      
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUSHER_NAME: binibot
        run: |
          npm config set access public
          git config --global user.email binibot@nosebit.com
          git config --global user.name binibot
          git remote set-url origin https://binibot:${{secrets.PUSHER_TOKEN}}@github.com/binibiz/eslint-config.git
          npx lerna publish --yes